spring:
  #DatasourceProperties----> mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: SFYchangeme150012.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 15
      min-idle: 15
      max-active: 15
      max-wait: 6000
