spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: SFYchangeme150012.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 6000
      initial-size: 10
      min-idle: 10
      max-active: 10

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#    global-config:
#      db-config:
#        logic-nic-delete-value: 1
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.feng.mybatisplusgenerator.entity
  configuration:
    use-generated-keys: true
    mapUnderscoreToCamelCase: true