spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: SFYchangeme150012.
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: com.feng.*
      filters: stata,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000




#      #    type: com.zaxxer.hikari.HikariDataSource
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations:  classpath:mybatis/mapper/*.xml